site_name: Wiki ARK
theme:
  name: material
nav:
  - Accueil: index.md
  - ğŸ¦– CrÃ©atures:
      - T-Rex: creatures/t-rex.md
      - Argentavis: creatures/argentavis.md
      - Giganotosaure: creatures/giganotosaure.md
      - Wyverne: creatures/wyverne.md
      - Boss : Dragon: creatures/boss-dragon.md
      - Volants: creatures/volants.md
      - Marins: creatures/marins.md
      - Fantastiques: creatures/fantastiques.md
  - âš”ï¸ Ã‰quipements:
      - Fusil Ã  pompe: equipements/fusil-a-pompe.md
      - Arc composite: equipements/arc-composite.md
      - Fusil Tek: equipements/fusil-tek.md
      - Lance-flammes: equipements/lance-flammes.md
      - Armure en chitine: equipements/armure-chitine.md
      - Armure Tek: equipements/armure-tek.md
      - Selle de T-Rex: equipements/selle-trex.md
      - Plateforme de Bronto: equipements/plateforme-bronto.md
      - Pioche en mÃ©tal: equipements/pioche-metal.md
  - ğŸ› ï¸ Commandes Admin:
      - Commandes dâ€™objets: admin/commandes-objets.md